workflows:
  flutter-app:
    name: Build Flutter app (Android + iOS)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - appstore_credentials   # ← (optionnel) pour publier sur App Store
        - keystore_credentials   # ← (optionnel) pour publier sur Play Store
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    scripts:
      - name: 🔄 Clean project
        script: |
          flutter clean
      - name: 📦 Get Flutter dependencies
        script: |
          flutter pub get
      - name: 📱 Build iOS
        script: |
          cd ios
          pod install --repo-update
          cd ..
          flutter build ios --release --no-codesign
      - name: 🤖 Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
      # Décommente si tu veux publier automatiquement
      # app_store_connect:
      #   api_key: $APP_STORE_API_KEY
      #   key_id: $APP_STORE_KEY_ID
      #   issuer_id: $APP_STORE_ISSUER_ID
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT
      #   track: internal

