// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORzI5-UmrnSY0hDJMNXtVXB_dpNyP9Fc',
    appId: '1:996341534126:android:f2a9b7ec9ed692a8170c3f',
    messagingSenderId: '996341534126',
    projectId: 'memorizbible',
    databaseURL: 'https://memorizbible-default-rtdb.firebaseio.com',
    storageBucket: 'memorizbible.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS7Yxx8tkwT56NzcskRcrnkS0JVX3l0B4',
    appId: '1:996341534126:ios:1acf875be6475906170c3f',
    messagingSenderId: '996341534126',
    projectId: 'memorizbible',
    databaseURL: 'https://memorizbible-default-rtdb.firebaseio.com',
    storageBucket: 'memorizbible.firebasestorage.app',
    iosBundleId: 'com.ulrichjosia.memorizbible',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHrPG0EyXWJHRnmnffuM8hU8Yk4GM9FU',
    appId: '1:996341534126:web:2e893d9858b59517170c3f',
    messagingSenderId: '996341534126',
    projectId: 'memorizbible',
    authDomain: 'memorizbible.firebaseapp.com',
    databaseURL: 'https://memorizbible-default-rtdb.firebaseio.com',
    storageBucket: 'memorizbible.firebasestorage.app',
    measurementId: 'G-WGQR186MH4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS7Yxx8tkwT56NzcskRcrnkS0JVX3l0B4',
    appId: '1:996341534126:ios:9536d5c4f46405cf170c3f',
    messagingSenderId: '996341534126',
    projectId: 'memorizbible',
    databaseURL: 'https://memorizbible-default-rtdb.firebaseio.com',
    storageBucket: 'memorizbible.firebasestorage.app',
    iosBundleId: 'com.example.memorizBible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHHrPG0EyXWJHRnmnffuM8hU8Yk4GM9FU',
    appId: '1:996341534126:web:32e9dd4b8bbbbf1c170c3f',
    messagingSenderId: '996341534126',
    projectId: 'memorizbible',
    authDomain: 'memorizbible.firebaseapp.com',
    databaseURL: 'https://memorizbible-default-rtdb.firebaseio.com',
    storageBucket: 'memorizbible.firebasestorage.app',
    measurementId: 'G-12P78MGQ7V',
  );

}